export default class Constants {
  static readonly FULL_LENGTH = '100%';
  static readonly COMMON_LENGTH = '90%';
  static readonly HALF_LENGTH = '50%';
  static readonly QUARTER_LENGTH = '25%';
  static readonly ONE_EIGHTH_LENGTH = '12.5%';
  static readonly SPACING_EXTRA_SMALL = 4;
  static readonly SPACING_SMALL = 8;
  static readonly SPACING_MEDIUM = 16;
  static readonly SPACING_LARGE = 32;
  static readonly SPACING_EXTRA_LARGE = 60;
  static readonly ZERO = 0;
  static readonly COLON = ':';
  static readonly SPACE = ' ';
  static readonly EMPTY_STRING = '';
  static readonly DASH = '-';
  static readonly SLASH = '/';
  static readonly DEGREE = '°';
}